### ISSUE TITLE
Missing Exeception

### ISSUE THREAD

**Issue by milanPansuriya** [Tap-Payments/goSellSDK-Android#1]
` FATAL EXCEPTION: main
                                                                                     	 Process: com.wmt.android.demo.walkentokendemo, PID: 28572 
											java.lang.IllegalArgumentException: bad base-64
                                                                                          at android.util.Base64.decode(Base64.java:161)
                                                                                          at android.util.Base64.decode(Base64.java:136)
                                                                                          at android.util.Base64.decode(Base64.java:118)
                                                                                          at company.tap.gosellapi.api.crypto.CryptoUtil.encrypt(CryptoUtil.java:35)
                                                                                          at company.tap.gosellapi.api.crypto.CryptoUtil.encryptJsonString(CryptoUtil.java:27)
                                                                                          at company.tap.gosellapi.api.requests.CardRequest$Builder.build(CardRequest.java:71)
                                                                                          at com.wmt.android.demo.walkentokendemo.activity.PaymentActivity.createToken(PaymentActivity.java:48)
                                                                                          at com.wmt.android.demo.walkentokendemo.activity.PaymentActivity.onClick(PaymentActivity.java:34)
                                                                                          at android.view.View.performClick(View.java:6294)
                                                                                          at android.view.View$PerformClick.run(View.java:24770)
                                                                                          at android.os.Handler.handleCallback(Handler.java:790)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by GoltsevEugene** [comment]
Dear @milanPansuriya , seems like your encryption key is invalid.
Did you copy the encryption key from your dashboard?
Has the application crashed?

**Comment by milanPansuriya** [comment]
@GoltsevEugene If I am using Gradle line than it crashes,
but if I am using as LIB project than it works
I think in Gradle Line project you missed `IllegalArgumentException ex` in CryptoUtil class line No.45

**Comment by GoltsevEugene** [comment]
@milanPansuriya, by Gradle Line you mean run project from console?
Actually, it doesn't crash, it prints stacktrace of exception - you can check line 43 in CryptoUtil class.

**Comment by milanPansuriya** [comment]
This class from Gradle 
`package company.tap.gosellapi.api.crypto;

import android.support.annotation.NonNull;
import android.support.annotation.RestrictTo;
import android.util.Base64;

import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;

import javax.crypto.Cipher;

/**
 * Created by eugene.goltsev on 16.02.2018.
 * <br>
 * Util class for RSA encryption
 */

@RestrictTo(RestrictTo.Scope.LIBRARY)
public final class CryptoUtil {
    public static String encryptJsonString(@NonNull String jsonString, String encryptionKey) {
        if(jsonString.length() == 0) {
            throw new IllegalArgumentException("Parameter jsonString cannot be empty");
        }

        return encrypt(jsonString, encryptionKey);
    }

    private static String encrypt(String encrypt, String encryptionKey) {
        String result = "";
        try {
            encryptionKey = encryptionKey.replaceAll("\\n", "").replace("-----BEGIN PUBLIC KEY-----", "").replace("-----END PUBLIC KEY-----", "");

            byte[] publicBytes = Base64.decode(encryptionKey, Base64.DEFAULT);
            X509EncodedKeySpec keySpec = new X509EncodedKeySpec(publicBytes);
            KeyFactory keyFactory = KeyFactory.getInstance("RSA");
            PublicKey pubKey = keyFactory.generatePublic(keySpec);
            Cipher encryptCipher = Cipher.getInstance("RSA/None/PKCS1Padding");
            encryptCipher.init(Cipher.ENCRYPT_MODE, pubKey);
            result = Base64.encodeToString(encryptCipher.doFinal(encrypt.getBytes()), Base64.DEFAULT).replaceAll("\\n", "");
        } catch (GeneralSecurityException ex) {
            ex.printStackTrace();
        }
        return result;
    }
}
`
And this class in Github 


`package company.tap.gosellapi.api.crypto;
import android.support.annotation.NonNull;
import android.support.annotation.RestrictTo;
import android.util.Base64;

import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;

import javax.crypto.Cipher;

/**
 * Created by eugene.goltsev on 16.02.2018.
 * <br>
 * Util class for RSA encryption
 */

@RestrictTo(RestrictTo.Scope.LIBRARY)
public final class CryptoUtil {
    public static String encryptJsonString(@NonNull String jsonString, String encryptionKey) {
        if(jsonString.length() == 0) {
            throw new IllegalArgumentException("Parameter jsonString cannot be empty");
        }

        return encrypt(jsonString, encryptionKey);
    }

    private static String encrypt(String encrypt, String encryptionKey) {
        String result = "";
        try {
            encryptionKey = encryptionKey.replaceAll("\\n", "").replace("-----BEGIN PUBLIC KEY-----", "").replace("-----END PUBLIC KEY-----", "");

            byte[] publicBytes = Base64.decode(encryptionKey, Base64.DEFAULT);
            X509EncodedKeySpec keySpec = new X509EncodedKeySpec(publicBytes);
            KeyFactory keyFactory = KeyFactory.getInstance("RSA");
            PublicKey pubKey = keyFactory.generatePublic(keySpec);
            Cipher encryptCipher = Cipher.getInstance("RSA/None/PKCS1Padding");
            encryptCipher.init(Cipher.ENCRYPT_MODE, pubKey);
            result = Base64.encodeToString(encryptCipher.doFinal(encrypt.getBytes()), Base64.DEFAULT).replaceAll("\\n", "");
        } catch (GeneralSecurityException|IllegalArgumentException ex) {
            ex.printStackTrace();
        }
        return result;
    }
}`

**Comment by GoltsevEugene** [comment]
Thanks a lot, @milanPansuriya!
Really weird behaviour and I don't have explanations for that.
At the moment I released version 1.0.3, where two exception types are splitted in different clauses, so I'm closing this issue.
