### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method apply(Lcom/bumptech/glide/request/RequestOptions;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/packagename-RUTD1SzmsMC0a3bnMHqDOQ==/split_lib_dependencies_apk.apk)

### ISSUE THREAD

**Issue by celikrecep** [Tap-Payments/goSellSDK-Android#24]
I have this error, when I clicked to the payButton. I use 4.9.0 version of Glide but The library use 4.7.1. I get this error when I use same version to library. "https://github.com/bumptech/glide/issues/3185" but solutions does not work for me. Can you update to Glide for library? 

 java.lang.NoSuchMethodError: No virtual method apply(Lcom/bumptech/glide/request/RequestOptions;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/packagename-RUTD1SzmsMC0a3bnMHqDOQ==/split_lib_dependencies_apk.apk)
        at company.tap.gosellapi.internal.activities.GoSellPaymentActivity.setupHeader(GoSellPaymentActivity.java:230)
        at company.tap.gosellapi.internal.activities.GoSellPaymentActivity.initViews(GoSellPaymentActivity.java:158)
        at company.tap.gosellapi.internal.activities.GoSellPaymentActivity.onCreate(GoSellPaymentActivity.java:142)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by HaithamSheshtawy** [comment]
Glide updated in 2.4.1
