### ISSUE TITLE
java.lang.NoSuchFieldException: PURCHASE

### ISSUE THREAD

**Issue by WajeehMoalem** [Tap-Payments/goSellSDK-Android#26]
debug version works fine
but the release version crashes when enabling proguard.

im using the latest goSellSdk version 2.4.2

this is what im getting in logcat when i launch the tap activity

2019-10-10 17:08:26.881 2617-2617/itssportsco.android.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: itssportsco.android.app, PID: 2617
    java.lang.AssertionError: java.lang.NoSuchFieldException: PURCHASE
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(:792)
        at com.google.gson.internal.bind.TypeAdapters$30.create(:818)
        at com.google.gson.Gson.getAdapter(:458)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(:102)
        at com.google.gson.Gson.getAdapter(:458)
        at retrofit2.converter.gson.GsonConverterFactory.a(:71)
        at retrofit2.Retrofit.a(:280)
        at retrofit2.Retrofit.a(:260)
        at retrofit2.RequestFactory$Builder.a(:706)
        at retrofit2.RequestFactory$Builder.a(:295)
        at retrofit2.RequestFactory$Builder.a(:182)
        at retrofit2.RequestFactory.a(:65)
        at retrofit2.ServiceMethod.a(:25)
        at retrofit2.Retrofit.a(:168)
        at retrofit2.Retrofit$1.invoke(:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy7.a(Unknown Source)
        at company.tap.gosellapi.internal.api.facade.GoSellAPI.a(:228)
        at company.tap.gosellapi.open.controllers.SDKSession.j(:389)
        at company.tap.gosellapi.open.controllers.SDKSession.c(:366)
        at company.tap.gosellapi.open.controllers.SDKSession.a(:327)
        at itssportsco.android.app.TapActivity.n(:261)
        at itssportsco.android.app.TapActivity.s(:108)
        at itssportsco.android.app.TapActivity.onCreate(:88)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.NoSuchFieldException: PURCHASE
        at java.lang.Class.getField(Class.java:1601)
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(:781)
        at com.google.gson.internal.bind.TypeAdapters$30.create(:818) 
        at com.google.gson.Gson.getAdapter(:458) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(:117) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(:166) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(:102) 
        at com.google.gson.Gson.getAdapter(:458) 
        at retrofit2.converter.gson.GsonConverterFactory.a(:71) 
        at retrofit2.Retrofit.a(:280) 
        at retrofit2.Retrofit.a(:260) 
        at retrofit2.RequestFactory$Builder.a(:706) 
        at retrofit2.RequestFactory$Builder.a(:295) 
        at retrofit2.RequestFactory$Builder.a(:182) 
        at retrofit2.RequestFactory.a(:65) 
        at retrofit2.ServiceMethod.a(:25) 
        at retrofit2.Retrofit.a(:168) 
        at retrofit2.Retrofit$1.invoke(:147) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
        at $Proxy7.a(Unknown Source) 
        at company.tap.gosellapi.internal.api.facade.GoSellAPI.a(:228) 
        at company.tap.gosellapi.open.controllers.SDKSession.j(:389) 
        at company.tap.gosellapi.open.controllers.SDKSession.c(:366) 
        at company.tap.gosellapi.open.controllers.SDKSession.a(:327) 
        at itssportsco.android.app.TapActivity.n(:261) 
        at itssportsco.android.app.TapActivity.s(:108) 
        at itssportsco.android.app.TapActivity.onCreate(:88) 
        at android.app.Activity.performCreate(Activity.java:7327) 
        at android.app.Activity.performCreate(Activity.java:7318) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 

*****************

this at ( itssportsco.android.app.TapActivity.n(:261) ) is pointing to this line of code:
sdkSession.start(this);
inside the configureSDKSession() function

*******************
these are my rules:

-dontwarn android.support.v7.**
-keep class android.support.v7.** { *; }
-keep interface android.support.v7.** { *; }

# support constraint
-dontwarn android.support.constraint.**
-keep class android.support.constraint.** { *; }
-keep interface android.support.constraint.** { *; }
-keep public class android.support.constraint.R$* { *; }

# support
-dontwarn android.support.**

# junit
-dontwarn org.junit.**

# support design
-dontwarn android.support.design.**
-keep class android.support.design.** { *; }
-keep interface android.support.design.** { *; }
-keep public class android.support.design.R$* { *; }

##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { <fields>; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * implements com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

##---------------End: proguard configuration for Gson  ----------

# Retrofit
-keep class com.google.gson.** { *; }
-keep public class com.google.gson.** {public private protected *;}
-keep class com.google.inject.** { *; }
-keep class org.apache.http.** { *; }
-keep class org.apache.james.mime4j.** { *; }
-keep class javax.inject.** { *; }
-keep class javax.xml.stream.** { *; }
-keep class retrofit.** { *; }
-keep class com.google.appengine.** { *; }
-keepattributes *Annotation*
-keepattributes Signature
-dontwarn com.squareup.okhttp.*
-dontwarn rx.**
-dontwarn javax.xml.stream.**
-dontwarn com.google.appengine.**

# glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep class * extends com.bumptech.glide.module.AppGlideModule {
 <init>(...);
}
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# Uncomment for DexGuard only
#-keepresourcexmlelements manifest/application/meta-data@value=GlideModule

# FB Login
-keepclassmembers class * implements java.io.Serializable {
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

-keepnames class com.facebook.FacebookActivity
-keepnames class com.facebook.CustomTabActivity

-keep class com.facebook.login.Login

# GoSellSdk

-keepattributes Signature
    -keepclassmembernames,allowobfuscation interface * {
        @retrofit2.http.* <methods>;
    }
    -dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

    #########################################################################
    # OkHttp
    #########################################################################
    -dontwarn okhttp3.**
    -dontwarn okhttp2.**
    -dontwarn okio.**
    -dontwarn javax.annotation.**
    -dontwarn org.conscrypt.**
    -keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# easy permission

-keepclassmembers class * {
    @pub.devrel.easypermissions.AfterPermissionGranted <methods>;
}

-keepnames class **

******************************************

**Comment by WajeehMoalem** [comment]
after editing the code a bit i came to this error
its working fine in debug version
but the release is still having issues

2019-10-11 16:24:58.876 12158-12256/itssportsco.android.app E/AndroidRuntime: FATAL EXCEPTION: GLThread 84623
    Process: itssportsco.android.app, PID: 12158
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at gotap.com.tapglkitandroid.gl.Views.TapRender.onSurfaceCreated(:50)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

**Comment by WajeehMoalem** [comment]
i removed unnecessary code taken from the example and it solved my problem

**Comment by HaithamSheshtawy** [comment]
Great.
