### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SearchView.setVisibility(int)' on a null object reference

### ISSUE THREAD

**Issue by mshafeekvly** [Tap-Payments/goSellSDK-Android#27]
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.widget.SearchView.setVisibility(int)' on a null object reference
        at company.tap.gosellapi.internal.activities.CurrenciesActivity.onCreateOptionsMenu(CurrenciesActivity.java:100)
        at android.app.Activity.onCreatePanelMenu(Activity.java:4074)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1589)
        at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:1869)
        at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:230)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by WajeehMoalem** [comment]
@HaithamSheshtawy can u please view my issue ?

**Comment by HaithamSheshtawy** [comment]
could u plaese integrate with "com.github.Tap-Payments:goSellSDK-AndroidX:3.2.1" and let me know .

**Comment by mshafeekvly** [comment]
I was using version 2.4.1. When I use "com.github.Tap-Payments:goSellSDK-AndroidX:3.2.1" it's working fine. Thank you for your reply.
