### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by navneetboghani** [Tap-Payments/goSellSDK-Android#42]
Fatal Exception: java.lang.NullPointerException

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String company.tap.gosellapi.internal.api.models.PaymentOption.getThreeDS()' on a null object reference
       at company.tap.gosellapi.internal.data_managers.PaymentProcessManager.callChargeOrAuthorizeOrSaveCardAPI(PaymentProcessManager.java:662)
       at company.tap.gosellapi.internal.data_managers.PaymentProcessManager.access$100(PaymentProcessManager.java:65)
       at company.tap.gosellapi.internal.data_managers.PaymentProcessManager$1.onSuccess(PaymentProcessManager.java:487)
       at company.tap.gosellapi.internal.data_managers.PaymentProcessManager$1.onSuccess(PaymentProcessManager.java:469)
       at company.tap.gosellapi.internal.api.callbacks.BaseCallback.onResponse(BaseCallback.java:36)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8387)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by AhlaamK-tap** [comment]
@navneetboghani  Could you please send the scenario you were performing when this error occurred? Also please let us know if it occurs regularly or was just once .
Please note to send above details on this email - **a.kazi@tap.company**
